### ISSUE TITLE
app is good request for traceroute feature

### ISSUE THREAD

**Issue by ashudb70** [tuz358/Simple-Ping-Tool#1]
hey can we get traceroute in your app? 
am using your code for my college project  i need info about traceroute adding to your app how can i do it any idea?

**Comment by tuz358** [comment]
Thanks for using my code!
As you can see from the code, I am using shell command to ping.
But traceroute command is available only root on Android.
So, how about implementing it in Java?

**Comment by ashudb70** [comment]
Using ping command can we get traceroute? Like there is library i guess if i share code can u help me in resolving where exactly is the bug

**Comment by tuz358** [comment]
Why don't you search for "Java traceroute"?
There are many sample programs.
It is important for you to do it on your own.

I'm also a freshman.
Let's do our best!
